// <auto-generated />
using Bean___Code.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bean___Code.Migrations
{
    [DbContext(typeof(BeanDbContext))]
    [Migration("20260113134247_dataseeding")]
    partial class dataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bean___Code.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Varma drycker"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kalla drycker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bakverk"
                        });
                });

            modelBuilder.Entity("Bean___Code.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "En stark italiensk kaffespecialitet",
                            Name = "Espresso",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Svart bryggt kaffe",
                            Name = "Coffe",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Mild kaffedrink med mycket mjölk",
                            Name = "Latte",
                            Price = 40m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "English breakfast",
                            Name = "Te",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "En klassiker direkt från New York",
                            Name = "Cheesecake",
                            Price = 45m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "En fruktig och kall svensk ikon",
                            Name = "Trocadero",
                            Price = 20m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Det bästa bakverket",
                            Name = "Kanelbulle",
                            Price = 40m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Klassisk fabrikat chokladboll",
                            Name = "Delicatoboll",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("Bean___Code.Models.Product", b =>
                {
                    b.HasOne("Bean___Code.Models.Category", "Category")
                        .WithMany("ProductConnection")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bean___Code.Models.Category", b =>
                {
                    b.Navigation("ProductConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
